spring:
  mail:
    host: smtp.qq.com
    username: 123@qq.com
    password: 授权码
    default-encoding: utf-8
    properties:
      mail.smtp.ssl.enable: true # qq需要配置ssl
  servlet:
    multipart:
      max-file-size: 100MB
      maxRequestSize: 100MB
  application:
    name: blog-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-init-sql: set names utf8mb4
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 密码
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.zhao.pojo
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
server:
  port: 8080
upload:
  local:
    # nginx映射本地文件路径
     url: http://ip:端口号
    # 本地文件存储路径
     path: /usr/local/upload/
